// Generate SIMULATED GMV Max spend so the decision layers can be demonstrated
// before the ad account is connected in Reacher.
//
//   node scripts/demo-spend.mjs            generate for every shop with data
//   node scripts/demo-spend.mjs --purge    delete every simulated row
//
// ── READ THIS BEFORE CHANGING ANYTHING HERE ────────────────────────────────
// This writes invented money into a database that otherwise contains only
// measured money. Three things keep that safe, and none of them are optional:
//
//   1. Every row is written with data_source = 'simulated'.
//   2. A database trigger refuses to let a shop hold simulated and measured
//      rows at once, so a half-real ROAS cannot be computed by accident.
//   3. Every reporting function returns data_source, and the UI stamps every
//      figure derived from it.
//
// The numbers are DETERMINISTIC — seeded from the shop id and the date — so the
// demo does not quietly change between one showing and the next.
//
// ── WHAT IS BEING SIMULATED, AND WHAT IS NOT ───────────────────────────────
// The revenue is real. Every day's measured ad-driven and organic GMV comes
// from actual classified order lines. Only the SPEND, and GMV Max's own
// reported revenue, are invented — and they are invented to reproduce the exact
// phenomenon this product exists to detect: a reporting platform that counts
// organic sales toward its own campaigns and therefore looks better than it is.
//
// It shows the mechanism. It does not predict the number.
import { createClient } from '@supabase/supabase-js';
import { need } from './_env.mjs';

const [URL, SERVICE] = need('VITE_SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY');
const db = createClient(URL, SERVICE, { auth: { persistSession: false } });

const PURGE = process.argv.includes('--purge');

// ── deterministic noise ─────────────────────────────────────────────────────
// A hash, not Math.random: the same shop and day must always produce the same
// figure, or the Boss sees different numbers on a second look at the same page.
function seeded(...parts) {
  let h = 2166136261;
  for (const s of parts.join('|')) { h ^= s.charCodeAt(0); h = Math.imul(h, 16777619); }
  return ((h >>> 0) % 100000) / 100000;   // 0..1
}

const { data: shops, error } = await db
  .from('shops').select('id, shop_name, currency').order('shop_name');
if (error) { console.error(error.message); process.exit(1); }

if (PURGE) {
  let removed = 0;
  for (const t of ['gmv_max_settings_changes', 'gmv_max_daily_metrics', 'gmv_max_campaigns']) {
    const { count, error: e } = await db.from(t).delete({ count: 'exact' }).eq('data_source', 'simulated');
    if (e) { console.error(`${t}: ${e.message}`); process.exit(1); }
    console.log(`  ${t.padEnd(28)} ${count ?? 0} simulated rows deleted`);
    removed += count ?? 0;
  }
  console.log(`\n${removed} simulated rows removed. Measured rows were not touched.`);
  process.exit(0);
}

for (const shop of shops) {
  // Real measured revenue per day — the spine the simulation hangs on.
  const { data: days, error: e } = await db.rpc('shop_affiliate_daily', {
    p_shop_id: shop.id,
    p_start: new Date(Date.now() - 45 * 864e5).toISOString().slice(0, 10),
    p_end: new Date().toISOString().slice(0, 10),
  });
  if (e) { console.log(`${shop.shop_name}: ${e.message}`); continue; }
  if (!days?.length) { console.log(`${shop.shop_name.padEnd(18)} no measured revenue — nothing to hang a simulation on`); continue; }

  // Refuse to sit on top of measured campaigns. The trigger would reject the
  // write anyway; failing here says why, before a half-written run.
  const { data: src } = await db.rpc('shop_data_sources', { p_shop_id: shop.id });
  if (src?.[0]?.has_measured) {
    console.log(`${shop.shop_name.padEnd(18)} SKIPPED — real GMV Max campaigns exist. Simulation would corrupt a measured ROAS.`);
    continue;
  }

  // The biggest product by measured revenue, so the campaign is about something
  // that actually exists in this shop.
  const { data: prods } = await db.rpc('shop_products', {
    p_shop_id: shop.id,
    p_start: days[0].day, p_end: days[days.length - 1].day, p_limit: 1,
  });
  const product = prods?.[0];

  const campaignId = `SIM-${String(shop.id).slice(0, 8)}`;
  const campaign = {
    shop_id: shop.id,
    campaign_id: campaignId,
    campaign_name: `[SIMULATED] ${product?.title?.slice(0, 40) || shop.shop_name} — Product GMV Max`,
    status: 'ENABLE',
    campaign_type: 'PRODUCT_GMV_MAX',
    product_id: product?.product_id ?? null,
    target_roas: 1.8,
    daily_budget: null,          // set below from the generated spend
    optimization_mode: 'SCHEDULE_FROM_NOW',
    currency: shop.currency || 'USD',
    data_source: 'simulated',
    raw: { simulated: true, note: 'Generated by scripts/demo-spend.mjs — not from Reacher.' },
  };

  const metrics = [];
  for (const d of days) {
    const paid = Number(d.paid_gmv) || 0;
    const organic = Number(d.organic_gmv) || 0;
    if (paid <= 0) continue;

    const r = seeded(shop.id, d.day);

    // ── the simulated world, built so the numbers are internally coherent ──
    // GMV Max buys three surfaces. Only the affiliate one leaves commission
    // evidence, so only its return can ever be verified.
    //
    // Spend is derived from the affiliate surface outward, not the other way
    // round: affiliate-surface spend is what produced the measured ad-driven
    // revenue, at a plausible efficiency; the other surfaces cost money and
    // produce revenue we cannot see.
    const affiliateRoas = 1.8 + r * 0.8;                 // 1.8 - 2.6
    const spendAffiliate = paid / affiliateRoas;
    const otherRatio = 0.5 + seeded(shop.id, d.day, 'mix') * 0.4;   // other surfaces cost 50-90% of affiliate
    const spendOther = spendAffiliate * otherRatio;

    // Deliberate budget variation across the window. Layer 5 (marginal ROAS)
    // needs spend that actually MOVES; against a flat budget the model would
    // correctly refuse to answer, so simulating one would demo a dead end.
    const phase = 1 + Math.sin(days.indexOf(d) / 4.2) * 0.28;
    const spend = (spendAffiliate + spendOther) * phase;

    // What GMV Max reports: the revenue it genuinely drove on the surfaces we
    // cannot measure, PLUS a share of organic sales it claims as its own. The
    // second term is the over-attribution this product exists to bound.
    const otherSurfaceRevenue = spendOther * phase * (1.5 + r * 0.8);
    const bleed = 0.32 + seeded(shop.id, d.day, 'bleed') * 0.18;
    const reported = paid + otherSurfaceRevenue + organic * bleed;

    const clicks = Math.round(spend / (0.34 + r * 0.22));
    const impressions = Math.round(clicks / (0.008 + r * 0.006));

    metrics.push({
      shop_id: shop.id,
      campaign_id: campaignId,
      day: d.day,
      spend: Number(spend.toFixed(2)),
      impressions,
      clicks,
      orders: Math.max(1, Math.round(Number(d.lines) * 0.42)),
      revenue: Number(reported.toFixed(2)),
      roi: Number((reported / spend).toFixed(4)),
      cpc: Number((spend / Math.max(clicks, 1)).toFixed(4)),
      cpm: Number(((spend / Math.max(impressions, 1)) * 1000).toFixed(4)),
      ctr: Number((clicks / Math.max(impressions, 1)).toFixed(6)),
      // Surfaces, consistent with how the spend above was derived.
      spend_affiliate: Number((spendAffiliate * phase).toFixed(2)),
      spend_product_card: Number((spendOther * phase * 0.72).toFixed(2)),
      spend_brand: Number((spendOther * phase * 0.28).toFixed(2)),
      data_source: 'simulated',
      raw: {
        simulated: true,
        affiliate_roas_used: Number(affiliateRoas.toFixed(3)),
        organic_bleed: Number(bleed.toFixed(3)),
        other_surface_revenue: Number(otherSurfaceRevenue.toFixed(2)),
      },
    });
  }

  if (!metrics.length) { console.log(`${shop.shop_name.padEnd(18)} no days with ad-driven revenue`); continue; }

  const avgSpend = metrics.reduce((a, x) => a + x.spend, 0) / metrics.length;
  campaign.daily_budget = Number((avgSpend * 1.25).toFixed(2));

  const { error: cErr } = await db.from('gmv_max_campaigns')
    .upsert(campaign, { onConflict: 'shop_id,campaign_id' });
  if (cErr) { console.log(`${shop.shop_name}: ${cErr.message}`); continue; }

  const { error: mErr } = await db.from('gmv_max_daily_metrics')
    .upsert(metrics, { onConflict: 'shop_id,campaign_id,day' });
  if (mErr) { console.log(`${shop.shop_name}: ${mErr.message}`); continue; }

  // A settings history, so campaign memory has something to evaluate.
  const mid = metrics[Math.floor(metrics.length / 2)];
  const early = metrics[Math.floor(metrics.length / 4)];
  const changes = [
    { changed_at: `${early.day}T09:00:00Z`, field: 'daily_budget',
      old_value: String((campaign.daily_budget * 0.7).toFixed(2)), new_value: String(campaign.daily_budget) },
    { changed_at: `${mid.day}T14:30:00Z`, field: 'target_roas', old_value: '1.60', new_value: '1.80' },
  ].map((c) => ({ ...c, shop_id: shop.id, campaign_id: campaignId, data_source: 'simulated', raw: { simulated: true } }));

  await db.from('gmv_max_settings_changes')
    .upsert(changes, { onConflict: 'shop_id,campaign_id,changed_at,field' });

  const { data: roas } = await db.rpc('shop_paid_roas', {
    p_shop_id: shop.id, p_start: metrics[0].day, p_end: metrics[metrics.length - 1].day,
  });
  const R = roas?.[0];
  const f = (v) => (v == null ? '—' : Number(v).toFixed(2));
  console.log(
    `${shop.shop_name.padEnd(18)} ${metrics.length} days · spend $${Number(R?.spend || 0).toFixed(0)}` +
    `  ·  GMV Max would claim ROI ${f(R?.reported_roi)}` +
    `  ·  proven floor ${f(R?.verified_roas)}` +
    `  ·  ${((Number(R?.unverified_share) || 0) * 100).toFixed(0)}% of the claim unevidenced`,
  );
}

console.log(`\nAll rows written with data_source = 'simulated'.`);
console.log(`Remove them with: npm run demo:purge`);
